version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore
      - run:
          name: build
          command: dotnet build --configuration Release --no-restore
      - run:
          name: Run tests
          command: dotnet test /p:CollectCoverage=true /p:IncludeTestAssembly=true /p:CoverletOutputFormat='json%2copencover' /p:CoverletOutput=../results/coverage /p:Threshold=0 /p:ThresholdType=${thresholdType} /p:MergeWith='../results/coverage.json' /p:CoverletOutputFormat=opencover

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
