version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore
      - run:
          name: build
          command: dotnet build --configuration Release --no-restore
      - run:
          name: Run tests
          command: dotnet test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
